- name: Launch EC2 instance
  hosts: localhost
  gather_facts: False
  vars_files:
    - params.yml
  tasks:
    - name: Create security group for our instance
      ec2_group:
        aws_access_key: "{{ aws_api_key }}"
        aws_secret_key: "{{ aws_api_secret }}"
        name: "{{ ec2_security_group }}"
        description: "{{ ec2_security_group_description }}"
        region: "{{ ec2_region }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: "{{ JENKINS.PORT }}"
            to_port: "{{ JENKINS.PORT }}"
            cidr_ip: 0.0.0.0/0
          - proto: icmp
            from_port: -1
            to_port: -1
            cidr_ip: 0.0.0.0/0

    - name: Launch instance
      ec2:
        id: "{{ ec2_instance_id }}"
        aws_access_key: "{{ aws_api_key }}"
        aws_secret_key: "{{ aws_api_secret }}"
        key_name: "{{ ec2_key_name }}"
        group: "{{ ec2_security_group }}"
        instance_type: "{{ ec2_instance_type }}"
        image: "{{ ec2_image }}"
        wait: true
        region: "{{ ec2_region }}"
        instance_tags: "{{ ec2_tags }}"
      register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
      with_items: "{{ ec2.instances }}"
      changed_when: False

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        timeout: 360
        state: started
      with_items: "{{ ec2.instances }}"

- name: Configure launched instance
  hosts: launched
  vars_files:
    - params.yml
  vars:
    ansible_ssh_private_key_file: "{{ private_key_path }}"
    initialAdminPassword_path: /var/lib/jenkins/secrets/initialAdminPassword
  remote_user: ec2-user
  become: True
  gather_facts: False
  tasks:
    - name: install Docker
      yum:
        name: docker
        state: latest

    - name: start Docker service
      service: name=docker enabled=yes state=started

    - name: install Java8
      yum: name=java-1.8.0 state=present

    - name: add Jenkins yum repo
      get_url:
        dest: /etc/yum.repos.d/jenkins.repo
        url:  https://pkg.jenkins.io/redhat/jenkins.repo

    - name: import Jenkins yum repo key
      rpm_key: key=https://pkg.jenkins.io/redhat/jenkins.io.key

    - name: install Jenkins
      yum: name=jenkins state=latest

    - name: set Jenkins params in /etc/sysconfig/jenkins
      lineinfile:
        path:   /etc/sysconfig/jenkins
        regexp: "^JENKINS_{{item.key}}="
        line:   "JENKINS_{{item.key}}=\"{{item.value}}\""
      with_dict: "{{ JENKINS }}"
      notify:
        - restart jenkins

    - name: start Jenkins service
      service: name=jenkins enabled=yes state=started

  handlers:
    - name: restart jenkins
      service: name=jenkins state=restarted

  post_tasks:
    - name: wait for Jenkins port
      wait_for:
        host: "{{ ansible_host }}"
        port: "{{ JENKINS.PORT }}"
        timeout: 10

    - name: wait until Jenkins creates initialAdminPassword
      wait_for:
        path: "{{ initialAdminPassword_path }}"
        timeout: 10

    - name: get Jenkins initial admin password
      command: cat "{{ initialAdminPassword_path }}"
      register: cat
      changed_when: False

    - name: print Jenkins URL
      debug:
        msg: "Jenkins URL: http://{{ansible_host}}:{{JENKINS.PORT}}/"

    - name: print Jenkins initial admin password
      vars:
        jpass:
          Jenkins_initial_admin_password: "{{ cat.stdout_lines[0] }}"
      debug: msg="{{ jpass }}"

